--ozone-platform=wayland
--ozone-platform-hint=wayland
--password-store=gnome-libsecret
--ignore-gpu-blocklist
--use-gl=angle
--use-angle=gl
--enable-features=TouchpadOverscrollHistoryNavigation,AcceleratedVideoDecodeLinuxGL,VaapiOnNvidiaGPUs
--load-extension=/usr/share/omarchy/default/chromium/extensions/copy-url,/usr/share/omarchy/default/chromium/extensions/yt-dlp,/usr/share/omarchy/default/chromium/extensions/whatsapp-slim
